os:
- linux
language: python
python:
- '3.5'
- '3.7'
- '3.8'

before_install:
- sudo apt-get update
- sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk texlive-luatex texlive-xetex
- pip install poetry

install:
- poetry install
script:
- poetry run nox

after_success:
- which python
- cd docs
- make latexpdf

